name: Build Linux Binary

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20' # You can change this to your desired Go version

    - name: Build
      run: |
        cd cmd
        GOOS=linux GOARCH=amd64 go build -o Domain_IP_Selector-linux-amd64 main.go

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: linux-binary
        path: cmd/Domain_IP_Selector-linux-amd64