name: Go Cross-Platform Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build for ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: windows
            arch: amd64
            output_name: Domain_IP_Selector.exe
          - os: linux
            arch: amd64
            output_name: Domain_IP_Selector_linux_amd64
          - os: linux
            arch: arm64
            output_name: Domain_IP_Selector_linux_arm64
          - os: darwin # macOS
            arch: amd64
            output_name: Domain_IP_Selector_darwin_amd64
          - os: darwin # macOS
            arch: arm64
            output_name: Domain_IP_Selector_darwin_arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24' # 从 go.mod 文件中获取

    - name: Build
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
      run: go build -o ${{ matrix.output_name }} ./cmd/main.go

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.output_name }}
        path: ${{ matrix.output_name }}
